/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ds;

import javax.swing.*;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (Exception ex) {
            showMessageDialog(null,ex.getMessage(),ex.getClass().getName(),ERROR_MESSAGE);
        }
    }

}
